# Site settings
title: Kodbit.se
email: kristofer@kodbit.se
description: > # description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kodbit.se" # the base hostname & protocol for your site
twitter_username: ikitfr
github_username:  kitfr
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
